name: prod

services:
  app:
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: app_prod
    ports:
      - "8082:8000"
    depends_on:
      - db
    env_file:
      - .env.prod
    command: sh -c "
      cp /app/docker/.env.prod /app/.env &&
      php artisan config:clear &&
      php artisan cache:clear &&
      php artisan config:cache &&
      php artisan key:generate --force &&
      php artisan config:clear &&
      sleep 10 &&
      php artisan migrate --force &&
      php -S 0.0.0.0:8000 -t public "
      
  db:
    image: postgres:15
    container_name: postgres_prod
    environment:
      POSTGRES_DB: gcs
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_prod_data:/var/lib/postgresql/data

volumes:
  postgres_prod_data: