name: prod

services:
  app:
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: app_prod
    ports:
      - "8082:8000"
    depends_on:
      - db
    env_file:
      - .env.prod
    command: sh -c "
      cp /app/docker/.env.prod /app/.env &&
      echo 'Esperando banco subir...' &&
      until nc -z postgres_prod 5432; do
        sleep 2;
      done &&
      echo 'Banco OK!' &&
      php artisan key:generate --force &&
      php artisan migrate --force &&
      php artisan serve --host=0.0.0.0 --port=8000 "

  db:
    image: postgres:15
    container_name: postgres_prod
    environment:
      POSTGRES_DB: gcs
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_prod_data:/var/lib/postgresql/data

volumes:
  postgres_prod_data: