name: homolog

services:
  app:
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: app_homolog
    ports:
      - "8081:8000"
    depends_on:
      - db
    env_file:
      - .env.homolog

  db:
    image: postgres:15
    container_name: postgres_homolog
    environment:
      POSTGRES_DB: gcs
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_homolog_data:/var/lib/postgresql/data

volumes:
  postgres_homolog_data: